from pydantic import BaseModel, Field, ConfigDict, field_validator, model_validator
from typing import List, Optional, ClassVar, Union

class WritingChangeSuggestion(BaseModel):
    """
    Represents a specific suggestion for revising a section during the writing phase,
    typically generated by a reflection agent after reviewing a draft.
    """
    section_id: str = Field(..., description="The ID of the section or subsection needing revision.")
    issue_description: str = Field(..., description="A clear description of the issue identified (e.g., repetition, lack of clarity, missing transition).")
    suggested_change: str = Field(..., description="Specific guidance on how to address the issue or what content should be added/modified.")
    priority: Union[int, str] = Field(default=1, description="Suggested priority for addressing the change (e.g., 1=High, 2=Medium, 3=Low).")

    @model_validator(mode='before')
    @classmethod
    def normalize_field_names(cls, data):
        """Normalize common LLM field name variations to expected names."""
        if not isinstance(data, dict):
            return data
        # Map common LLM variations -> expected field names
        aliases = {
            'issue_description': ['description', 'issue', 'problem', 'issue_desc',
                                  'feedback', 'comment', 'reason', 'critique',
                                  'finding', 'analysis', 'assessment', 'note',
                                  'observation', 'concern', 'explanation'],
            'suggested_change': ['suggestion', 'change', 'recommended_change', 'fix',
                                 'recommendation', 'action', 'proposed_change',
                                 'improvement', 'revision', 'solution'],
            'section_id': ['section', 'id', 'target_section', 'section_name'],
        }
        for target, sources in aliases.items():
            if target not in data:
                for src in sources:
                    if src in data:
                        data[target] = data.pop(src)
                        break

        # Last resort: if issue_description still missing, use any remaining string value
        if 'issue_description' not in data:
            known_keys = {'section_id', 'suggested_change', 'priority', 'issue_description'}
            for key, val in list(data.items()):
                if key not in known_keys and isinstance(val, str) and len(val) > 10:
                    data['issue_description'] = data.pop(key)
                    break

        # If suggested_change still missing, duplicate issue_description
        if 'suggested_change' not in data and 'issue_description' in data:
            data['suggested_change'] = data['issue_description']

        return data

    @field_validator('priority', mode='before')
    @classmethod
    def coerce_priority(cls, v):
        """Accept both int and string priorities from LLMs (e.g., 'high', 'medium', 'low')."""
        if isinstance(v, int):
            return v
        if isinstance(v, str):
            mapping = {'high': 1, 'critical': 1, 'medium': 2, 'moderate': 2, 'low': 3, 'minor': 3}
            lower = v.strip().lower()
            if lower in mapping:
                return mapping[lower]
            try:
                return int(v)
            except ValueError:
                return 2  # Default to medium
        return 1

    model_config: ClassVar[ConfigDict] = ConfigDict(extra='ignore')  # Tolerate extra fields from LLMs
    # Removed old Pydantic v1 Config to avoid conflict with model_config
    # class Config:
    #     schema_extra = {
    #         "example": {
    #             "section_id": "lit_review_sub_ai_ethics",
    #             "issue_description": "The paragraph discussing algorithmic bias feels disconnected from the previous point on data privacy.",
    #             "suggested_change": "Add a sentence or two to bridge the discussion, perhaps mentioning how data privacy concerns can exacerbate bias issues.",
    #             "priority": 1
    #         }
    #     }

class WritingReflectionOutput(BaseModel):
    """
    Output schema for the agent reflecting on a written draft.
    """
    overall_assessment: str = Field(..., description="A brief overall assessment of the draft's quality, coherence, and adherence to the outline/goals.")
    change_suggestions: List[WritingChangeSuggestion] = Field(default_factory=list, description="A list of specific, actionable suggestions for revision.")
    scratchpad_update: str = Field(..., description="A concise summary of the reflection step to be added to the agent scratchpad.")
    # --- Added field for thought_pad ---
    generated_thought: Optional[str] = Field(None, description="A concise thought or reminder generated by the agent to be added to the thought_pad.")
    # --- End added field ---

    model_config: ClassVar[ConfigDict] = ConfigDict(extra='ignore')  # Tolerate extra fields from LLMs
    # Removed old Pydantic v1 Config to avoid conflict with model_config
    # class Config:
    #     schema_extra = {
    #         "example": {
    #             "overall_assessment": "The draft covers the main points well, but flow between sections could be improved, and some repetition exists in the methodology section.",
    #             "change_suggestions": [
    #                 {
    #                     "section_id": "methodology",
    #                     "issue_description": "Repetitive explanation of the data collection process.",
    #                     "suggested_change": "Consolidate the description of data collection into the first paragraph and remove the redundant explanation later in the section.",
    #                     "priority": 1
    #                 },
    #                 {
    #                     "section_id": "conclusion",
    #                     "issue_description": "Transition from the discussion section is abrupt.",
    #                     "suggested_change": "Add a sentence at the beginning of the conclusion to summarize the key findings discussed previously before stating the final conclusions.",
    #                     "priority": 2
    #                 }
    #             ],
    #             "scratchpad_update": "Reviewed draft, identified 2 key issues: repetition in methodology and abrupt transition to conclusion.",
    #             "generated_thought": "Report needs smoother transitions between sections; methodology section contains redundant information that should be consolidated."
    #         }
    #     }
