package repo

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"

	"github.com/Cyb3rDudu/axiom/axiom-ng/internal/models"
)

// DocumentGroup is the handler-facing view of a document_groups row.
type DocumentGroup struct {
	ID              uuid.UUID  `json:"id"`
	UserID          int32      `json:"user_id"`
	Name            string     `json:"name"`
	Description     string     `json:"description,omitempty"`
	SourceMissionID *uuid.UUID `json:"source_mission_id,omitempty"`
	AutoGenerated   bool       `json:"auto_generated"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

// DocumentGroupSummary is the lightweight shape used for the list
// endpoint — keeps the M2M join out of the payload.
type DocumentGroupSummary struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Description   string    `json:"description,omitempty"`
	DocumentCount int64     `json:"document_count"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// ErrGroupHasActiveMissions is returned when deleting a group that is
// still referenced by pending/running/paused missions.
var ErrGroupHasActiveMissions = errors.New("repo: document group has active missions")

// DocumentGroups owns document_groups + association CRUD.
type DocumentGroups struct{ gdb *gorm.DB }

// NewDocumentGroups wires the repo to the DB.
func NewDocumentGroups(gdb *gorm.DB) *DocumentGroups { return &DocumentGroups{gdb: gdb} }

// Create inserts a new group.
func (g *DocumentGroups) Create(ctx context.Context, userID int32, name, description string) (DocumentGroup, error) {
	now := time.Now().UTC()
	m := models.DocumentGroup{
		ID:        uuid.New(),
		UserID:    userID,
		Name:      name,
		CreatedAt: now,
		UpdatedAt: now,
	}
	if description != "" {
		m.Description = &description
	}
	if err := g.gdb.WithContext(ctx).Create(&m).Error; err != nil {
		return DocumentGroup{}, err
	}
	return groupFromModel(m), nil
}

// List returns summaries (no documents M2M join) scoped to userID.
func (g *DocumentGroups) List(ctx context.Context, userID int32, skip, limit int) ([]DocumentGroupSummary, error) {
	if limit < 1 || limit > 500 {
		limit = 100
	}
	if skip < 0 {
		skip = 0
	}
	var rows []models.DocumentGroup
	err := g.gdb.WithContext(ctx).
		Where("user_id = ?", userID).
		Order("updated_at DESC").
		Limit(limit).
		Offset(skip).
		Find(&rows).Error
	if err != nil {
		return nil, err
	}
	out := make([]DocumentGroupSummary, 0, len(rows))
	for _, r := range rows {
		count, err := g.documentCount(ctx, r.ID)
		if err != nil {
			return nil, err
		}
		desc := ""
		if r.Description != nil {
			desc = *r.Description
		}
		out = append(out, DocumentGroupSummary{
			ID:            r.ID,
			Name:          r.Name,
			Description:   desc,
			DocumentCount: count,
			CreatedAt:     r.CreatedAt,
			UpdatedAt:     r.UpdatedAt,
		})
	}
	return out, nil
}

// Get returns a single group by id scoped to userID.
func (g *DocumentGroups) Get(ctx context.Context, userID int32, id uuid.UUID) (DocumentGroup, error) {
	var m models.DocumentGroup
	err := g.gdb.WithContext(ctx).Where("id = ? AND user_id = ?", id, userID).First(&m).Error
	if err != nil {
		return DocumentGroup{}, mapErr(err)
	}
	return groupFromModel(m), nil
}

// Update changes name and/or description. Empty strings leave the
// previous value untouched; matches the Python behavior where missing
// fields in the request body aren't applied.
func (g *DocumentGroups) Update(ctx context.Context, userID int32, id uuid.UUID, name, description string, setDescription bool) (DocumentGroup, error) {
	upd := map[string]any{"updated_at": time.Now().UTC()}
	if name != "" {
		upd["name"] = name
	}
	if setDescription {
		if description == "" {
			upd["description"] = nil
		} else {
			upd["description"] = description
		}
	}
	res := g.gdb.WithContext(ctx).Model(&models.DocumentGroup{}).
		Where("id = ? AND user_id = ?", id, userID).
		Updates(upd)
	if res.Error != nil {
		return DocumentGroup{}, res.Error
	}
	if res.RowsAffected == 0 {
		return DocumentGroup{}, ErrNotFound
	}
	return g.Get(ctx, userID, id)
}

// Delete removes the group, failing when active missions still refer to
// it. Matches axiom_backend/database/crud.py:delete_document_group.
func (g *DocumentGroups) Delete(ctx context.Context, userID int32, id uuid.UUID) error {
	return g.gdb.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		var active int64
		err := tx.Model(&models.Mission{}).
			Joins("JOIN chats c ON c.id = missions.chat_id").
			Where("c.user_id = ? AND missions.status IN ? AND missions.generated_document_group_id = ?",
				userID, []string{"pending", "running", "paused"}, id).
			Count(&active).Error
		if err != nil {
			return err
		}
		if active > 0 {
			return ErrGroupHasActiveMissions
		}
		res := tx.Where("id = ? AND user_id = ?", id, userID).Delete(&models.DocumentGroup{})
		if res.Error != nil {
			return res.Error
		}
		if res.RowsAffected == 0 {
			return ErrNotFound
		}
		return nil
	})
}

// AddDocument attaches a doc owned by userID to the group. Silent no-op
// if the association already exists.
func (g *DocumentGroups) AddDocument(ctx context.Context, userID int32, groupID, docID uuid.UUID) error {
	return g.gdb.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := assertOwnership(tx, userID, groupID, docID); err != nil {
			return err
		}
		return tx.Exec(`
			INSERT INTO document_group_association (document_id, document_group_id)
			VALUES (?, ?)
			ON CONFLICT (document_id, document_group_id) DO NOTHING`,
			docID, groupID).Error
	})
}

// RemoveDocument detaches a doc from a group.
func (g *DocumentGroups) RemoveDocument(ctx context.Context, userID int32, groupID, docID uuid.UUID) error {
	return g.gdb.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := assertOwnership(tx, userID, groupID, docID); err != nil {
			return err
		}
		return tx.Where("document_id = ? AND document_group_id = ?", docID, groupID).
			Delete(&models.DocumentGroupAssociation{}).Error
	})
}

// BulkAddDocuments attempts to add each doc; returns the ones added and
// a per-id failure map.
func (g *DocumentGroups) BulkAddDocuments(ctx context.Context, userID int32, groupID uuid.UUID, docIDs []uuid.UUID) ([]uuid.UUID, map[uuid.UUID]error) {
	ok := make([]uuid.UUID, 0, len(docIDs))
	fail := map[uuid.UUID]error{}
	for _, id := range docIDs {
		if err := g.AddDocument(ctx, userID, groupID, id); err != nil {
			fail[id] = err
		} else {
			ok = append(ok, id)
		}
	}
	return ok, fail
}

// BulkRemoveDocuments attempts to remove each doc; returns the ones
// removed and a per-id failure map.
func (g *DocumentGroups) BulkRemoveDocuments(ctx context.Context, userID int32, groupID uuid.UUID, docIDs []uuid.UUID) ([]uuid.UUID, map[uuid.UUID]error) {
	ok := make([]uuid.UUID, 0, len(docIDs))
	fail := map[uuid.UUID]error{}
	for _, id := range docIDs {
		if err := g.RemoveDocument(ctx, userID, groupID, id); err != nil {
			fail[id] = err
		} else {
			ok = append(ok, id)
		}
	}
	return ok, fail
}

// documentCount counts M2M rows for a group.
func (g *DocumentGroups) documentCount(ctx context.Context, groupID uuid.UUID) (int64, error) {
	var n int64
	err := g.gdb.WithContext(ctx).Model(&models.DocumentGroupAssociation{}).
		Where("document_group_id = ?", groupID).
		Count(&n).Error
	return n, err
}

// assertOwnership verifies both the group and document belong to userID.
// Returns ErrNotFound otherwise, so handlers uniformly map to 404.
func assertOwnership(tx *gorm.DB, userID int32, groupID, docID uuid.UUID) error {
	var groupExists, docExists int64
	if err := tx.Model(&models.DocumentGroup{}).
		Where("id = ? AND user_id = ?", groupID, userID).Count(&groupExists).Error; err != nil {
		return err
	}
	if groupExists == 0 {
		return ErrNotFound
	}
	if err := tx.Model(&models.Document{}).
		Where("id = ? AND user_id = ?", docID, userID).Count(&docExists).Error; err != nil {
		return err
	}
	if docExists == 0 {
		return ErrNotFound
	}
	return nil
}

func groupFromModel(m models.DocumentGroup) DocumentGroup {
	g := DocumentGroup{
		ID:            m.ID,
		UserID:        m.UserID,
		Name:          m.Name,
		AutoGenerated: m.AutoGenerated,
		CreatedAt:     m.CreatedAt,
		UpdatedAt:     m.UpdatedAt,
	}
	if m.Description != nil {
		g.Description = *m.Description
	}
	if m.SourceMissionID != nil {
		g.SourceMissionID = m.SourceMissionID
	}
	return g
}
